# Description: This file contains various stellarium settings used for controlling the simulation
#   1. Fix Time 
#       - Set time to J2000
#       - Set time rate to 0
#       - Advance time to 2451545.
#       - Stars will be fixed in their positions
#   2. Rotate camera on equatorial mount 
#       - Rotation only about Y and Z 
#       - Pitch and Yaw, no roll
#   3. Set fov
#       - Calculate Intrinsic
#       - Calculate Extrinsic at every frame
#       - Calculate all star pixel positions in camera frame (X/Y Pixel)
#       - Check if in frame using bounds)
#
# Note: By not advancing time, all stars retain their positions
#   By caching RA and DEC, we can quickly look up camera pixel positions
#


# Stellarium Camera Settings
fov: 8.0 # 44.2
#aperture: 0.0125
aperture: 0.0125 # 1.0
# width: 6480
# height: 4860
width: 1024
height: 768
# width: 2048
# height: 1536

# Stellarium Time Settings
gregorian_date: "2024-02-03 12:00:00.000"
# gregorian_date: "2001-01-01 12:00:00.000"
# gregorian_date: "1991-04-02 03:56:23.317"
timerate: 0.0

# Stellarium Location Settings
latitude: 0.0  # 90.0
longitude: 0.0
altitude: 1000.0

# Slew Right
ra_steps: 200
# ra_start: -3.14
# ra_end: 3.14
ra_start: -3.141592653589793
ra_end: 3.141592653589793
# ra_start: -1.5707963267948966
# ra_end: -1.5707963267948966
# ra_end: 1.5707963267948966

dec_steps: 200
# dec_start: 1.5
# dec_end: 1.5
# dec_start: 0
# dec_end: 1.5707963267948966
# dec_start: 1.5707963267948966
# dec_end: 1.5707963267948966
dec_start: 1.5
dec_end: -1.5

delay_sec: 0.01
# delay_sec: 1.0

# Min Constraint on magnitude
min_magnitude_thresh: 9.0
# Max Constraint on magnitude
max_magnitude_thresh: 0.0

# Stellarium API URLs
url_main: "http://localhost:7624/api/"
url_status: "main/status"
url_view: "main/view"
url_view_skyculture: "view/skyculturedescription/"
url_projection: "view/listprojection"
url_fov: "main/fov"
url_time: "main/time"
url_actions: "stelaction/list"
url_do_action: "stelaction/do"
url_prop: "stelproperty/list"
url_prop_set: "stelproperty/set"
url_location: "api/location"
url_simbad: "simbad/lookup"
url_objecttypes: "objects/listobjecttypes"
url_listobjectsbytype: "objects/listobjectsbytype"
url_objectinfo: "objects/info"


disabled_properties: [
    "actionShow_Atmosphere",
    "actionShow_Ground",
    "actionShow_Fog",
    "actionShow_Gridlines",
    "actionShow_Cardinal_Points",
    "actionShow_Intercardinal_Points",
    "actionShow_LandscapeLabels",
    "actionShow_LandscapeIllumination",
    "actionShow_MeteorShowers_labels",
    "actionShow_Night_Mode",
    "actionShow_Oculars_GUI",
    "actionShow_Skyculture_NativePlanetNames",
    "actionShow_Planets_Labels",
    "actionShow_Planets_Pointers",
    "actionShow_Satellite_Hints",
    "actionShow_Satellite_Labels",
    "actionShow_Satellite_ConfigDialog_Global",
    "actionShow_Hips_Surveys",
    "actionShow_Planets_Trails",
    "actionShow_Planets_Orbits",
    "actionShow_DSO_Textures",
    "actionSet_Full_Screen_Global",
    # Things that may need to be configurable
    "actionShow_MilkyWay",
    "actionShow_MeteorShowers",
    "actionShow_Planets",
    "actionShow_Nebulas",
    "actionShow_ZodiacalLight",
    "StelSkyDrawer.flagDrawBigStarHalo",
    "StelSkyDrawer.flagStarTwinkle",
    # GUI Controls for debug
    "actionToggle_GuiHidden_Global",
    "actionShow_Stars_Labels",#
]

enabled_properties: [
    "StelMovementMgr.equatorialMount",
    "StelSkyDrawer.flagStarMagnitudeLimit",
    "StelSkyDrawer.flagPlanetMagnitudeLimit",
    "StelSkyDrawer.flagNebulaMagnitudeLimit",
    # This setting seems to double whatever the requested custom sizes are. Could change code but likely want to look into stellarium..
    #"MainView.flagUseCustomScreenshotSize", 
  ]


# # Some Settings that may be interesting
# # "MainView.skyBackgroundColor"
# # "MainView.screenshotDpi"
# #    "MainView.screenShotFormat": {
# #    "MainView.screenShotFileMask": {
# #    "MainView.flagScreenshotDateFileName": {
# #    "ObsListDialog.flagUseFov": {
# #    "Oculars.enableCCD": {
# #    "Oculars.enableOcular": {
# #    "Oculars.flagAutoLimitMagnitude": {
# #    "Oculars.flagAutosetMountForCCD": {
# #    "Oculars.flagInitFOVUsage": {
# #    "Oculars.flagMaxExposureTimeForCCD": {
# #    "Oculars.selectedCCDRotationAngle": {
# #    "Oculars.selectedLensIndex": {
# #    "Oculars.selectedOcularIndex": {
