#include "opencv2/opencv.hpp"
#include <string>
#include <iostream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <sys/stat.h>
#include <fstream>
#include <inttypes.h>
#include <memory>
#include <array>
#include <math.h>
#include <eigen3/Eigen/Dense>
#include <chrono>
#include <ctime>
#include <assert.h>
#include <math.h>
#include <algorithm>
#include <functional>
#include <experimental/filesystem>
#include <list>
#include <unordered_map>
#include <vector>